build script refinements
 - add --nowatch option to esbuild-rollup-dev so it can be used for
   one-off direct building of the StellarContracts rollup-plugin to dist/
   - moved withDocs helper around to support this case ^

 - DEBUGGER=1 to force node debugger with rollup
 - DEBUG=1 now only adds full debug diagnostics in rollup
 - scripts/debugRollup still uses node debugger implicitly,
   with full debug diagnostics

 - mac compat: mktemp XXXX at end of template string
 - mac compat: /usr/bin/env bash

diff --git a/scripts/build b/scripts/build
--- a/scripts/build
+++ b/scripts/build
@@ -1,4 +1,4 @@
-#!/bin/bash
+#!/usr/bin/env bash
 # set -x # debug mode
 #set -e # exit on error
 #//! EXPECTS to be run in context of `pnpm exec`
@@ -7,12 +7,8 @@ srcDir=$(dirname $0)
 STC_PROJECT_PITCH=0
 . $srcDir/support.sh
 
-WITHDOCS=${DOCS:-1}
 startTime=$(date)
 
-withDocs() {
-    [[ $WITHDOCS -eq 0 ]] || $*
-}
 
 
 programDTS() {
@@ -55,13 +51,16 @@ playStartSound &
 }  
 
 echo "In foreground: rollup main code bundle" 
-./scripts/rollup
+./scripts/rollup || {
+    echo "error in rollup main code bundle"
+    logProblemWith "rollup main code bundle"
+    wait
+    exit 42
+}
 
 sleep 0.5
 echo "------------------------------ waiting ------------------------------"
 wait
-
-exitIfError
 playCheckpointSound
 
 {
