smokeBuild - wait for tsc before building docs
 - Fixes the issue where type-only changes don't arrive
   without restarting the build script
 - no need to delete the .d.ts file during build
 - no interference with downstream project's types during build
 - no need to restart downstream project's TS server after build

 + sound cues for hands-free feedback

diff --git a/scripts/smokeBuild b/scripts/smokeBuild
--- a/scripts/smokeBuild
+++ b/scripts/smokeBuild
@@ -1,39 +1,84 @@
 #!/bin/bash
 
-rm dist/stellar-contracts.d.ts
+playSound() {
+    if [ -f /usr/share/sounds/gnome/default/alerts/$1.ogg ]; then
+        play /usr/share/sounds/gnome/default/alerts/$1.ogg > /dev/null 2>&1
+    fi
+}
+# rm dist/stellar-contracts.d.ts > /dev/null 2>&1
+playSound swing
 
+tmpfile1=$(mktemp /tmp/XXXXXX.tsc.txt)
 set -e
-tsc &
+tsc > $tmpfile1 2>&1 &
 typecheck=$!
 
 # make a temp file
-tmpfile=$(mktemp /tmp/XXXXXX.ts)
+tmpfile2=$(mktemp /tmp/XXXXXX.api-extractor.txt)
 
 if [ "$SMOKE" != "" ]; then {
+    playSound hum
+
     pnpm smoke:test &
     smokeTest=$!
-    api-extractor run --local --verbose > $tmpfile 2>&1 &
+    if ! wait $typecheck; then {
+        echo '---------- TYPESCRIPT ERRORS ---------'
+        # play gnome click sound
+        playSound click
+        # play gnome hum sound
+        playSound hum
+
+        cat $tmpfile1
+        wait $smokeTest
+        echo '---------- TYPESCRIPT ERRORS ---------'
+        playSound hum &
+        sleep 0.5
+        playSound click &
+        sleep 0.5
+        playSound click
+
+        cat $tmpfile1
+        rm $tmpfile1 $tmpfile2  > /dev/null 2>&1
+        exit 1
+    } fi
+    # play gnome hum sound
+    playSound hum &
+    sleep 0.2
+    playSound hum
+    api-extractor run --local --verbose > $tmpfile2 2>&1 &
     docs=$!
     if wait $smokeTest ; then {
         echo "Smoke test passed"
-        cat $tmpfile
+        cat $tmpfile2
     } else {
         echo "Smoke test failed"
         # cat $tmpfile
-        exit 1
+        # exit 1
     } fi
 
 } else {
+    if ! wait $typecheck; then {
+        echo '---------- TYPESCRIPT ERRORS --------- '
+        playSound click &
+        sleep 0.5
+        playSound click &
+        cat $tmpfile1
+        rm $tmpfile1 $tmpfile2  > /dev/null 2>&1
+        exit 1
+    } fi
+    playSound hum & 
     api-extractor run --local --verbose  &
     docs=$!
 } fi
 
 wait $docs
 
-if ! wait $typecheck; then {
-    echo '---------- TYPESCRIPT ERRORS --------- '
-    tsc
-    exit 1
-} fi
 
 
+
+echo "  -- TYPESCRIPT check OK -- "
+cat $tmpfile1
+rm $tmpfile1 $tmpfile2  > /dev/null 2>&1
+playSound hum &
+sleep 0.5
+playSound string
